### ISSUE TITLE
locale of subject in project approval mail is wrong

### ISSUE THREAD

**Issue by JSchmieta** [FosterFork/FosterFork#4]

**Comment by zonque** [comment]
This one is strange. How are you testing, and are you sure you are using the latest version?

**Comment by JSchmieta** [comment]
I just received a mail when I was trying to save the different options. One of them was the approval, so yes it should be the current version. The main Text in in my locale, just the subject is in english instead.

**Comment by JSchmieta** [comment]
I just tried it with a new project. Now both subject and text are in the right locale

**Comment by zonque** [comment]
Yes, I fixed it. Good catch, thanks!
